version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=chatapp.settings
    volumes:
      - .:/app
    depends_on:
      - redis
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && uvicorn chatapp.asgi:application --host 0.0.0.0 --port 8000"
    networks:
      - chat-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - chat-network

  minio:
    image: minio/minio
    container_name: minio_chatapp
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_INIT_BUCKET: ${MINIO_BUCKET_NAME}
    volumes:
      - ./data:/data
    command:
      - server /data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./static:/app/static
    depends_on:
      - web
    networks:
      - chat-network

  openssl:
    image: alpine/openssl
    volumes:
      - ./certs:/certs
    command: >
      req -x509 -nodes -newkey rsa:4096 -keyout /certs/nginx.key
      -out /certs/nginx.crt -days 365
      -subj "/C=UA/ST=State/L=Kharkiv/O=Hillel/OU=Lecture/CN=localhost"

volumes:
  redis-data:

networks:
  chat-network:
    driver: bridge